services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./server/staticfiles:/app/staticfiles
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=djangoproj.settings
      - DATABASE_API_URL=http://database_api:3030
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - frontend
      - database_api

  frontend:
    build:
      context: ./server/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    command: npm start

  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db

  database_api:
    build:
      context: ./server/database
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    depends_on:
      - mongo_db
    environment:
      - MONGODB_URI=mongodb://mongo_db:27017/dealershipsDB

volumes:
  mongo_data: {} 